package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	graphql1 "github.com/toyohashi6140/eenen-api/domain/models/graphql"
	graphql2 "github.com/toyohashi6140/eenen-api/infra/graphql"
)

// FetchFakeLyrics is the resolver for the FetchFakeLyrics field.
func (r *queryResolver) FetchLyrics(ctx context.Context) ([]*graphql1.Lyric, error) {
	return r.LyricUsecase.FetchByKey(ctx)
}

// Query returns graphql2.QueryResolver implementation.
func (r *Resolver) Query() graphql2.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
